#+TITLE: Disc2
Hello everyone!
My major is nutrition, and some of the jobs I have looked at are Dietician, Sports Nutritionist, and Nutrition Consultent. This major is deisgned to prepare you for the graduate program in nutrition and dietetics. The goal of the graduate program is to eventually recieve the accreditation of Registered Dietitian Nutritionist. During this program you start doing hands-on work during your junior year, and will continue until the end of your fifth year in the program. This hands-on practice allows students like me to gain valuable experience within our own community in actual medial practice. As students we will also have the opportunity to mentor undergraduates, which will help us grow our own leadership skills in a job enironment.

When it comes to writing as a Dietician one of the most important documents will be meal plans or dietary restirictions before or after surgery or other medical event. These documents need to be very easy to understand so that the patient has a very high chance of completly following the provided plan. Keeping the content of the document simple yet thurough will most likely be the greatest challenge. I anticipate these documents will recieve a lot of focus during the coming years of my education, with plenty of opportunities to practice the writing style.

Another type of document I anticipate writing will be both internal and external communication with other medical professionals. Wether this be pre-surgery communication of current condition, or writing documents for check-ups or further recommendation. In these documents I will need to communicate in a consise manner in order to make sure that other members of the medical team can get all the information they need from one document.
