#+TITLE: Writing Assignment #1
#+AUTHOR: Jackson Mowry
#+DATE:2022-01-28 Fri
#+SETUPFILE: /home/jarch/Downloads/jake-latex-standard.setup
    From as early as I can remember math has always been easy for me. During elementary school I was tested for the program known as TAG (Talented and Gifted). After taking both tests I was placed on an accelerated learing path that continued on until my last year of high school. Starting in Elementary school I was part of a small group of students that would seperate from the class during math block so that we could work ahead and learn more advanced topics.  In the sixth grade I took a class equilivent to the eighth grade math class where we focused on pre-algebra and other topics. I have always like algebra mostly for solving systems of equations, and applying this technique to real problems, I think solving systems of equations is just how my brain works. By the next year we had move on to geometry which was not my best subject in math. At the time the basic trigonometry concepts were confusing to me, and it took until almost the end of the year for me to get them down. After that year I took algebra II, algebra has always been a strong suit of mine so this class was very easy for me to succeed in. Moving into High School meant taking Trigonometry which once again was a struggle for me to understand. The concepts of sin, cos, tan, and their applications were always difficult for me, but I was able to pass the class. After that I took pre-calculus which was also fairly easy, and I can see a lot of similarities with that class and MATH 141. After pre-calculus I took Statistics which did not go well for me. For whatever reason I consistently struggled in this class and was just able to earn a B after the final. At this point in my education I was burnt out and done with math, so for the next two years I took easier math classes, Financial Algebra, and Probability. These two classes made me really enjoy math again, and I was very happy that I took them.

    Now that I am working towards a CS minor I have to take a few more math classes. Starting with Math 141, and I am really excited to be learning math again. I am feeling really positive about Math 141 and I hope I can do well in the class. The one thing I am nervous about is the fact that I havent taken a math class in almost 2 years, so I am afraid that I will have forgotten some of the things I learned in pre-calc.
